language: python

os:
    - linux
    - osx

python:
    - 3.5


notifications:
  email: false

git:
  depth: 1

install:
    - pip -q install coveralls
    - python setup.py develop


script:
    - coverage run test/test.py

after_success:
    - coveralls
