language: python

python:
    - 3.5

matrix:
  include:
    - os: osx
#     language: generic
      osx_image: xcode7.3
      before_install:
        - brew update
#      script:
#        - swift build
    - os: linux
#      language: generic
      sudo: required
      dist: trusty
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        - chmod +x miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH=$HOME/miniconda/bin:$PATH 

notifications:
  email: false

git:
  depth: 1

install:
    - pip -q install coveralls
    - python setup.py develop


script:
    - coverage run test/test.py

after_success:
    - coveralls
